//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Useers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zxcEntities : DbContext
    {
        public zxcEntities()
            : base("name=zxcEntities")
        {
        }
        
        private static zxcEntities userEntities1 = new zxcEntities();

        public static zxcEntities GetContext()
        {
            if (userEntities1 == null)
            {
                userEntities1 = new zxcEntities();
            }
            return userEntities1;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
    }
}
